### ISSUE TITLE
Push notification not work on app closed

### ISSUE THREAD

**Issue by sy-per** [kugiigi/pesbuk-app#8]
-------------------------------------------------------
Bug
-------------------------------------------------------
## Device
- Meizu Pro 5
- Stable
- OTA 11

## Steps to Reproduce
1. active push
2. close app
3. wait ...

If the application is in background mode the notifications work well.

**Comment by kugiigi** [comment]
Unfortunately the push notification implementation in the app is just a workaround and there's nothing we can do about. Proper push notification needs to be implemented by Facebook. For now, app needs to be running in the background for it to work.

**Comment by sy-per** [comment]
Ok, it could be interesting to use this:
https://stackoverflow.com/questions/7854678/getting-all-notifications
with a token to put in the parameter.

**Comment by kugiigi** [comment]
Hmm, not sure about that but it looks something we can use. However, this isn't really something that should be implemented in the app. UT doesn't currently allow background processes from apps so maybe this is something that should be implemented with a proper notification framework in the system.

**Comment by poVoq** [comment]
@kugiigi could you point me to the place to modify in your code so that I could add a similar workaround to one of my apps? I understand the limitations of this approach, but it seems like the best I can do for now. It just intercepts the browser notifications, so that another Website/webapp could work the same, or is it using some facebook specific thing?

Thanks!

**Comment by kugiigi** [comment]
> @kugiigi could you point me to the place to modify in your code so that I could add a similar workaround to one of my apps? I understand the limitations of this approach, but it seems like the best I can do for now. It just intercepts the browser notifications, so that another Website/webapp could work the same, or is it using some facebook specific thing?
> 
> Thanks!

I don't think this is the best place to discuss this but I'm answering anyway 😄 
My code is very specific to facebook's mobile site because I add watchers to check HTML elements in the web page and see if there are notification badges. Actually, it doesn't seem to work now even if the app does not suspend. I'm not sure if the new QtWebEngine caused it or just the facebook mobile site.

**Comment by poVoq** [comment]
Hmm, so very much a custom thing. Ah, I guess I will not be able to get that working with this Javascript only webapp I was thinking about. Thanks anyways :+1:
